/*
 * OPayments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.opayments.sdk.api;

import io.opayments.sdk.ApiException;
import io.opayments.sdk.model.Balance;
import io.opayments.sdk.model.Error;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for BalanceApi
 */
@Disabled
public class BalanceApiTest {

    private final BalanceApi api = new BalanceApi();

    
    /**
     * Получить баланс
     *
     * Возвращает текущий баланс проекта.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getBalanceTest() throws ApiException {
        Balance response = 
        api.getBalance();
        
        // TODO: test validations
    }
    
}
