/*
 * OPayments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.opayments.sdk.api;

import io.opayments.sdk.ApiException;
import io.opayments.sdk.model.Error;
import java.time.OffsetDateTime;
import io.opayments.sdk.model.PaymentDetails;
import io.opayments.sdk.model.PaymentList;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for PaymentsApi
 */
@Disabled
public class PaymentsApiTest {

    private final PaymentsApi api = new PaymentsApi();

    
    /**
     * Получить платёж
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPaymentTest() throws ApiException {
        UUID paymentId = null;
        PaymentDetails response = 
        api.getPayment(paymentId);
        
        // TODO: test validations
    }
    
    /**
     * Найти платежи
     *
     * Возвращает список платежей проекта.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listPaymentsTest() throws ApiException {
        String orderId = null;
        List<String> status = null;
        String paymentMethod = null;
        Integer amountFrom = null;
        Integer amountTo = null;
        OffsetDateTime createdFrom = null;
        OffsetDateTime createdTo = null;
        String sort = null;
        String sortDirection = null;
        String cursor = null;
        Integer limit = null;
        PaymentList response = 
        api.listPayments(orderId, status, paymentMethod, amountFrom, amountTo, createdFrom, createdTo, sort, sortDirection, cursor, limit);
        
        // TODO: test validations
    }
    
}
