/*
 * OPayments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.opayments.sdk.api;

import io.opayments.sdk.ApiException;
import io.opayments.sdk.model.CreateSbpPaymentRequest;
import io.opayments.sdk.model.CreateTpayPaymentRequest;
import io.opayments.sdk.model.CreatedPayment;
import io.opayments.sdk.model.Error;
import io.opayments.sdk.model.Payment;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for PaymentApi
 */
@Disabled
public class PaymentApiTest {

    private final PaymentApi api = new PaymentApi();

    
    /**
     * Создать платёж по СБП
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createSbpPaymentTest() throws ApiException {
        CreateSbpPaymentRequest createSbpPaymentRequest = null;
        Payment response = 
        api.createSbpPayment(createSbpPaymentRequest);
        
        // TODO: test validations
    }
    
    /**
     * Создать платёж через T-Pay
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createTpayPaymentTest() throws ApiException {
        CreateTpayPaymentRequest createTpayPaymentRequest = null;
        Payment response = 
        api.createTpayPayment(createTpayPaymentRequest);
        
        // TODO: test validations
    }
    
}
