/*
 * OPayments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.opayments.sdk.api;

import io.opayments.sdk.ApiException;
import io.opayments.sdk.model.CreateRefundRequest;
import io.opayments.sdk.model.Error;
import io.opayments.sdk.model.PendingRefund;
import io.opayments.sdk.model.Refund;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for RefundsApi
 */
@Disabled
public class RefundsApiTest {

    private final RefundsApi api = new RefundsApi();

    
    /**
     * Создать возврат
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createPaymentRefundTest() throws ApiException {
        UUID paymentId = null;
        CreateRefundRequest createRefundRequest = null;
        Refund response = 
        api.createPaymentRefund(paymentId, createRefundRequest);
        
        // TODO: test validations
    }
    
    /**
     * Получить возврат
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPaymentRefundTest() throws ApiException {
        UUID paymentId = null;
        Refund response = 
        api.getPaymentRefund(paymentId);
        
        // TODO: test validations
    }
    
}
