/*
 * OPayments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.opayments.sdk.api;

import io.opayments.sdk.ApiClient;
import io.opayments.sdk.ApiException;
import io.opayments.sdk.ApiResponse;
import io.opayments.sdk.Configuration;
import io.opayments.sdk.Pair;

import io.opayments.sdk.model.Error;
import java.time.OffsetDateTime;
import io.opayments.sdk.model.PaymentDetails;
import io.opayments.sdk.model.PaymentList;
import java.util.UUID;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-07T05:37:00.661163339Z[Etc/UTC]", comments = "Generator version: 7.26.0-SNAPSHOT")
public class PaymentsApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public PaymentsApi() {
    this(Configuration.getDefaultApiClient());
  }

  public PaymentsApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Получить платёж
   * 
   * @param paymentId  (required)
   * @return PaymentDetails
   * @throws ApiException if fails to make API call
   */
  public PaymentDetails getPayment(@javax.annotation.Nonnull UUID paymentId) throws ApiException {
    return getPayment(paymentId, null);
  }

  /**
   * Получить платёж
   * 
   * @param paymentId  (required)
   * @param headers Optional headers to include in the request
   * @return PaymentDetails
   * @throws ApiException if fails to make API call
   */
  public PaymentDetails getPayment(@javax.annotation.Nonnull UUID paymentId, Map<String, String> headers) throws ApiException {
    ApiResponse<PaymentDetails> localVarResponse = getPaymentWithHttpInfo(paymentId, headers);
    return localVarResponse.getData();
  }

  /**
   * Получить платёж
   * 
   * @param paymentId  (required)
   * @return ApiResponse&lt;PaymentDetails&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PaymentDetails> getPaymentWithHttpInfo(@javax.annotation.Nonnull UUID paymentId) throws ApiException {
    return getPaymentWithHttpInfo(paymentId, null);
  }

  /**
   * Получить платёж
   * 
   * @param paymentId  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;PaymentDetails&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PaymentDetails> getPaymentWithHttpInfo(@javax.annotation.Nonnull UUID paymentId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getPaymentRequestBuilder(paymentId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getPayment", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<PaymentDetails>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        PaymentDetails responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<PaymentDetails>() {});
        

        return new ApiResponse<PaymentDetails>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getPaymentRequestBuilder(@javax.annotation.Nonnull UUID paymentId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'paymentId' is set
    if (paymentId == null) {
      throw new ApiException(400, "Missing the required parameter 'paymentId' when calling getPayment");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/payments/{paymentId}"
        .replace("{paymentId}", ApiClient.urlEncode(paymentId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Найти платежи
   * Возвращает список платежей проекта.
   * @param orderId Идентификатор заказа в системе мерчанта. (optional)
   * @param status  (optional)
   * @param paymentMethod  (optional)
   * @param amountFrom Не больше amountTo, если он передан. (optional)
   * @param amountTo Не меньше amountFrom, если он передан. (optional)
   * @param createdFrom Не позже createdTo, если он передан. (optional)
   * @param createdTo Не раньше createdFrom, если он передан. (optional)
   * @param sort  (optional, default to createdAt)
   * @param sortDirection  (optional, default to desc)
   * @param cursor Непрозрачный курсор из предыдущего ответа. Используйте только с теми же фильтрами и сортировкой. (optional)
   * @param limit Количество записей в ответе. (optional, default to 20)
   * @return PaymentList
   * @throws ApiException if fails to make API call
   */
  public PaymentList listPayments(@javax.annotation.Nullable String orderId, @javax.annotation.Nullable List<String> status, @javax.annotation.Nullable String paymentMethod, @javax.annotation.Nullable Integer amountFrom, @javax.annotation.Nullable Integer amountTo, @javax.annotation.Nullable OffsetDateTime createdFrom, @javax.annotation.Nullable OffsetDateTime createdTo, @javax.annotation.Nullable String sort, @javax.annotation.Nullable String sortDirection, @javax.annotation.Nullable String cursor, @javax.annotation.Nullable Integer limit) throws ApiException {
    return listPayments(orderId, status, paymentMethod, amountFrom, amountTo, createdFrom, createdTo, sort, sortDirection, cursor, limit, null);
  }

  /**
   * Найти платежи
   * Возвращает список платежей проекта.
   * @param orderId Идентификатор заказа в системе мерчанта. (optional)
   * @param status  (optional)
   * @param paymentMethod  (optional)
   * @param amountFrom Не больше amountTo, если он передан. (optional)
   * @param amountTo Не меньше amountFrom, если он передан. (optional)
   * @param createdFrom Не позже createdTo, если он передан. (optional)
   * @param createdTo Не раньше createdFrom, если он передан. (optional)
   * @param sort  (optional, default to createdAt)
   * @param sortDirection  (optional, default to desc)
   * @param cursor Непрозрачный курсор из предыдущего ответа. Используйте только с теми же фильтрами и сортировкой. (optional)
   * @param limit Количество записей в ответе. (optional, default to 20)
   * @param headers Optional headers to include in the request
   * @return PaymentList
   * @throws ApiException if fails to make API call
   */
  public PaymentList listPayments(@javax.annotation.Nullable String orderId, @javax.annotation.Nullable List<String> status, @javax.annotation.Nullable String paymentMethod, @javax.annotation.Nullable Integer amountFrom, @javax.annotation.Nullable Integer amountTo, @javax.annotation.Nullable OffsetDateTime createdFrom, @javax.annotation.Nullable OffsetDateTime createdTo, @javax.annotation.Nullable String sort, @javax.annotation.Nullable String sortDirection, @javax.annotation.Nullable String cursor, @javax.annotation.Nullable Integer limit, Map<String, String> headers) throws ApiException {
    ApiResponse<PaymentList> localVarResponse = listPaymentsWithHttpInfo(orderId, status, paymentMethod, amountFrom, amountTo, createdFrom, createdTo, sort, sortDirection, cursor, limit, headers);
    return localVarResponse.getData();
  }

  /**
   * Найти платежи
   * Возвращает список платежей проекта.
   * @param orderId Идентификатор заказа в системе мерчанта. (optional)
   * @param status  (optional)
   * @param paymentMethod  (optional)
   * @param amountFrom Не больше amountTo, если он передан. (optional)
   * @param amountTo Не меньше amountFrom, если он передан. (optional)
   * @param createdFrom Не позже createdTo, если он передан. (optional)
   * @param createdTo Не раньше createdFrom, если он передан. (optional)
   * @param sort  (optional, default to createdAt)
   * @param sortDirection  (optional, default to desc)
   * @param cursor Непрозрачный курсор из предыдущего ответа. Используйте только с теми же фильтрами и сортировкой. (optional)
   * @param limit Количество записей в ответе. (optional, default to 20)
   * @return ApiResponse&lt;PaymentList&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PaymentList> listPaymentsWithHttpInfo(@javax.annotation.Nullable String orderId, @javax.annotation.Nullable List<String> status, @javax.annotation.Nullable String paymentMethod, @javax.annotation.Nullable Integer amountFrom, @javax.annotation.Nullable Integer amountTo, @javax.annotation.Nullable OffsetDateTime createdFrom, @javax.annotation.Nullable OffsetDateTime createdTo, @javax.annotation.Nullable String sort, @javax.annotation.Nullable String sortDirection, @javax.annotation.Nullable String cursor, @javax.annotation.Nullable Integer limit) throws ApiException {
    return listPaymentsWithHttpInfo(orderId, status, paymentMethod, amountFrom, amountTo, createdFrom, createdTo, sort, sortDirection, cursor, limit, null);
  }

  /**
   * Найти платежи
   * Возвращает список платежей проекта.
   * @param orderId Идентификатор заказа в системе мерчанта. (optional)
   * @param status  (optional)
   * @param paymentMethod  (optional)
   * @param amountFrom Не больше amountTo, если он передан. (optional)
   * @param amountTo Не меньше amountFrom, если он передан. (optional)
   * @param createdFrom Не позже createdTo, если он передан. (optional)
   * @param createdTo Не раньше createdFrom, если он передан. (optional)
   * @param sort  (optional, default to createdAt)
   * @param sortDirection  (optional, default to desc)
   * @param cursor Непрозрачный курсор из предыдущего ответа. Используйте только с теми же фильтрами и сортировкой. (optional)
   * @param limit Количество записей в ответе. (optional, default to 20)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;PaymentList&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PaymentList> listPaymentsWithHttpInfo(@javax.annotation.Nullable String orderId, @javax.annotation.Nullable List<String> status, @javax.annotation.Nullable String paymentMethod, @javax.annotation.Nullable Integer amountFrom, @javax.annotation.Nullable Integer amountTo, @javax.annotation.Nullable OffsetDateTime createdFrom, @javax.annotation.Nullable OffsetDateTime createdTo, @javax.annotation.Nullable String sort, @javax.annotation.Nullable String sortDirection, @javax.annotation.Nullable String cursor, @javax.annotation.Nullable Integer limit, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listPaymentsRequestBuilder(orderId, status, paymentMethod, amountFrom, amountTo, createdFrom, createdTo, sort, sortDirection, cursor, limit, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listPayments", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<PaymentList>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        PaymentList responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<PaymentList>() {});
        

        return new ApiResponse<PaymentList>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listPaymentsRequestBuilder(@javax.annotation.Nullable String orderId, @javax.annotation.Nullable List<String> status, @javax.annotation.Nullable String paymentMethod, @javax.annotation.Nullable Integer amountFrom, @javax.annotation.Nullable Integer amountTo, @javax.annotation.Nullable OffsetDateTime createdFrom, @javax.annotation.Nullable OffsetDateTime createdTo, @javax.annotation.Nullable String sort, @javax.annotation.Nullable String sortDirection, @javax.annotation.Nullable String cursor, @javax.annotation.Nullable Integer limit, Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/payments";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "orderId";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("orderId", orderId));
    localVarQueryParameterBaseName = "status";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("multi", "status", status));
    localVarQueryParameterBaseName = "paymentMethod";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("paymentMethod", paymentMethod));
    localVarQueryParameterBaseName = "amountFrom";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("amountFrom", amountFrom));
    localVarQueryParameterBaseName = "amountTo";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("amountTo", amountTo));
    localVarQueryParameterBaseName = "createdFrom";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("createdFrom", createdFrom));
    localVarQueryParameterBaseName = "createdTo";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("createdTo", createdTo));
    localVarQueryParameterBaseName = "sort";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("sort", sort));
    localVarQueryParameterBaseName = "sortDirection";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("sortDirection", sortDirection));
    localVarQueryParameterBaseName = "cursor";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("cursor", cursor));
    localVarQueryParameterBaseName = "limit";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("limit", limit));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
