/*
 * OPayments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.opayments.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.opayments.sdk.model.TpayDeviceData;
import java.net.URI;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateTpayPaymentRequest
 */
class CreateTpayPaymentRequestTest {
    private final CreateTpayPaymentRequest model = new CreateTpayPaymentRequest();

    /**
     * Model tests for CreateTpayPaymentRequest
     */
    @Test
    void testCreateTpayPaymentRequest() {
        // TODO: test CreateTpayPaymentRequest
    }

    /**
     * Test the property 'orderId'
     */
    @Test
    void orderIdTest() {
        // TODO: test orderId
    }

    /**
     * Test the property 'amount'
     */
    @Test
    void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'currency'
     */
    @Test
    void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'ip'
     */
    @Test
    void ipTest() {
        // TODO: test ip
    }

    /**
     * Test the property 'callbackUrl'
     */
    @Test
    void callbackUrlTest() {
        // TODO: test callbackUrl
    }

    /**
     * Test the property 'successUrl'
     */
    @Test
    void successUrlTest() {
        // TODO: test successUrl
    }

    /**
     * Test the property 'failedUrl'
     */
    @Test
    void failedUrlTest() {
        // TODO: test failedUrl
    }

    /**
     * Test the property 'deviceData'
     */
    @Test
    void deviceDataTest() {
        // TODO: test deviceData
    }

}
