/*
 * OPayments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.opayments.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DeviceData
 */
class DeviceDataTest {
    private final DeviceData model = new DeviceData();

    /**
     * Model tests for DeviceData
     */
    @Test
    void testDeviceData() {
        // TODO: test DeviceData
    }

    /**
     * Test the property 'platformType'
     */
    @Test
    void platformTypeTest() {
        // TODO: test platformType
    }

    /**
     * Test the property 'os'
     */
    @Test
    void osTest() {
        // TODO: test os
    }

    /**
     * Test the property 'browser'
     */
    @Test
    void browserTest() {
        // TODO: test browser
    }

    /**
     * Test the property 'language'
     */
    @Test
    void languageTest() {
        // TODO: test language
    }

    /**
     * Test the property 'timezoneName'
     */
    @Test
    void timezoneNameTest() {
        // TODO: test timezoneName
    }

    /**
     * Test the property 'userAgent'
     */
    @Test
    void userAgentTest() {
        // TODO: test userAgent
    }

}
