/*
 * OPayments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.opayments.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FinalPayment
 */
class FinalPaymentTest {
    private final FinalPayment model = new FinalPayment();

    /**
     * Model tests for FinalPayment
     */
    @Test
    void testFinalPayment() {
        // TODO: test FinalPayment
    }

    /**
     * Test the property 'paymentId'
     */
    @Test
    void paymentIdTest() {
        // TODO: test paymentId
    }

    /**
     * Test the property 'orderId'
     */
    @Test
    void orderIdTest() {
        // TODO: test orderId
    }

    /**
     * Test the property 'amount'
     */
    @Test
    void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'currency'
     */
    @Test
    void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'paymentMethod'
     */
    @Test
    void paymentMethodTest() {
        // TODO: test paymentMethod
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'paymentUrl'
     */
    @Test
    void paymentUrlTest() {
        // TODO: test paymentUrl
    }

    /**
     * Test the property 'expiresAt'
     */
    @Test
    void expiresAtTest() {
        // TODO: test expiresAt
    }

    /**
     * Test the property 'failureCode'
     */
    @Test
    void failureCodeTest() {
        // TODO: test failureCode
    }

    /**
     * Test the property 'failureMessage'
     */
    @Test
    void failureMessageTest() {
        // TODO: test failureMessage
    }

    /**
     * Test the property 'completedAt'
     */
    @Test
    void completedAtTest() {
        // TODO: test completedAt
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    void updatedAtTest() {
        // TODO: test updatedAt
    }

}
