/*
 * OPayments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.opayments.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.opayments.sdk.model.Payment;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PaymentList
 */
class PaymentListTest {
    private final PaymentList model = new PaymentList();

    /**
     * Model tests for PaymentList
     */
    @Test
    void testPaymentList() {
        // TODO: test PaymentList
    }

    /**
     * Test the property 'items'
     */
    @Test
    void itemsTest() {
        // TODO: test items
    }

    /**
     * Test the property 'nextCursor'
     */
    @Test
    void nextCursorTest() {
        // TODO: test nextCursor
    }

    /**
     * Test the property 'hasMore'
     */
    @Test
    void hasMoreTest() {
        // TODO: test hasMore
    }

}
