/*
 * OPayments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.opayments.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PendingRefund
 */
class PendingRefundTest {
    private final PendingRefund model = new PendingRefund();

    /**
     * Model tests for PendingRefund
     */
    @Test
    void testPendingRefund() {
        // TODO: test PendingRefund
    }

    /**
     * Test the property 'paymentId'
     */
    @Test
    void paymentIdTest() {
        // TODO: test paymentId
    }

    /**
     * Test the property 'amount'
     */
    @Test
    void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'currency'
     */
    @Test
    void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'reason'
     */
    @Test
    void reasonTest() {
        // TODO: test reason
    }

    /**
     * Test the property 'failureCode'
     */
    @Test
    void failureCodeTest() {
        // TODO: test failureCode
    }

    /**
     * Test the property 'failureMessage'
     */
    @Test
    void failureMessageTest() {
        // TODO: test failureMessage
    }

    /**
     * Test the property 'acceptedAt'
     */
    @Test
    void acceptedAtTest() {
        // TODO: test acceptedAt
    }

    /**
     * Test the property 'declinedAt'
     */
    @Test
    void declinedAtTest() {
        // TODO: test declinedAt
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    void updatedAtTest() {
        // TODO: test updatedAt
    }

}
