/*
 * OPayments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.opayments.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.opayments.sdk.model.FinalRefund;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RefundWebhookNotification
 */
class RefundWebhookNotificationTest {
    private final RefundWebhookNotification model = new RefundWebhookNotification();

    /**
     * Model tests for RefundWebhookNotification
     */
    @Test
    void testRefundWebhookNotification() {
        // TODO: test RefundWebhookNotification
    }

    /**
     * Test the property 'notificationId'
     */
    @Test
    void notificationIdTest() {
        // TODO: test notificationId
    }

    /**
     * Test the property 'notificationType'
     */
    @Test
    void notificationTypeTest() {
        // TODO: test notificationType
    }

    /**
     * Test the property 'notificationDate'
     */
    @Test
    void notificationDateTest() {
        // TODO: test notificationDate
    }

    /**
     * Test the property 'paymentId'
     */
    @Test
    void paymentIdTest() {
        // TODO: test paymentId
    }

    /**
     * Test the property 'refund'
     */
    @Test
    void refundTest() {
        // TODO: test refund
    }

}
