/*
 * OPayments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.opayments.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.opayments.sdk.model.DeviceData;
import java.net.URI;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.opayments.sdk.ApiClient;
/**
 * CreateSbpPaymentRequest
 */
@JsonPropertyOrder({
  CreateSbpPaymentRequest.JSON_PROPERTY_ORDER_ID,
  CreateSbpPaymentRequest.JSON_PROPERTY_AMOUNT,
  CreateSbpPaymentRequest.JSON_PROPERTY_CURRENCY,
  CreateSbpPaymentRequest.JSON_PROPERTY_DESCRIPTION,
  CreateSbpPaymentRequest.JSON_PROPERTY_IP,
  CreateSbpPaymentRequest.JSON_PROPERTY_CALLBACK_URL,
  CreateSbpPaymentRequest.JSON_PROPERTY_SUCCESS_URL,
  CreateSbpPaymentRequest.JSON_PROPERTY_FAILED_URL,
  CreateSbpPaymentRequest.JSON_PROPERTY_DEVICE_DATA
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-07T05:37:00.661163339Z[Etc/UTC]", comments = "Generator version: 7.26.0-SNAPSHOT")
public class CreateSbpPaymentRequest {
  public static final String JSON_PROPERTY_ORDER_ID = "orderId";
  @javax.annotation.Nonnull
  private String orderId;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  @javax.annotation.Nonnull
  private Integer amount;

  /**
   * Gets or Sets currency
   */
  public enum CurrencyEnum {
    RUB(String.valueOf("RUB"));

    private String value;

    CurrencyEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static CurrencyEnum fromValue(String value) {
      for (CurrencyEnum b : CurrencyEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @javax.annotation.Nonnull
  private CurrencyEnum currency;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_IP = "ip";
  @javax.annotation.Nonnull
  private String ip;

  public static final String JSON_PROPERTY_CALLBACK_URL = "callbackUrl";
  @javax.annotation.Nonnull
  private URI callbackUrl;

  public static final String JSON_PROPERTY_SUCCESS_URL = "successUrl";
  @javax.annotation.Nonnull
  private URI successUrl;

  public static final String JSON_PROPERTY_FAILED_URL = "failedUrl";
  @javax.annotation.Nonnull
  private URI failedUrl;

  public static final String JSON_PROPERTY_DEVICE_DATA = "deviceData";
  @javax.annotation.Nullable
  private DeviceData deviceData;

  public CreateSbpPaymentRequest() { 
  }

  public CreateSbpPaymentRequest orderId(@javax.annotation.Nonnull String orderId) {
    this.orderId = orderId;
    return this;
  }

  /**
   * Идентификатор заказа в системе мерчанта.
   * @return orderId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ORDER_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getOrderId() {
    return orderId;
  }


  @JsonProperty(value = JSON_PROPERTY_ORDER_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOrderId(@javax.annotation.Nonnull String orderId) {
    this.orderId = orderId;
  }


  public CreateSbpPaymentRequest amount(@javax.annotation.Nonnull Integer amount) {
    this.amount = amount;
    return this;
  }

  /**
   * Сумма в копейках.
   * minimum: 1
   * @return amount
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AMOUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getAmount() {
    return amount;
  }


  @JsonProperty(value = JSON_PROPERTY_AMOUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmount(@javax.annotation.Nonnull Integer amount) {
    this.amount = amount;
  }


  public CreateSbpPaymentRequest currency(@javax.annotation.Nonnull CurrencyEnum currency) {
    this.currency = currency;
    return this;
  }

  /**
   * Get currency
   * @return currency
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public CurrencyEnum getCurrency() {
    return currency;
  }


  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCurrency(@javax.annotation.Nonnull CurrencyEnum currency) {
    this.currency = currency;
  }


  public CreateSbpPaymentRequest description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public CreateSbpPaymentRequest ip(@javax.annotation.Nonnull String ip) {
    this.ip = ip;
    return this;
  }

  /**
   * IP-адрес плательщика: IPv4 или IPv6.
   * @return ip
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_IP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getIp() {
    return ip;
  }


  @JsonProperty(value = JSON_PROPERTY_IP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIp(@javax.annotation.Nonnull String ip) {
    this.ip = ip;
  }


  public CreateSbpPaymentRequest callbackUrl(@javax.annotation.Nonnull URI callbackUrl) {
    this.callbackUrl = callbackUrl;
    return this;
  }

  /**
   * HTTPS-адрес уведомлений.
   * @return callbackUrl
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CALLBACK_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public URI getCallbackUrl() {
    return callbackUrl;
  }


  @JsonProperty(value = JSON_PROPERTY_CALLBACK_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCallbackUrl(@javax.annotation.Nonnull URI callbackUrl) {
    this.callbackUrl = callbackUrl;
  }


  public CreateSbpPaymentRequest successUrl(@javax.annotation.Nonnull URI successUrl) {
    this.successUrl = successUrl;
    return this;
  }

  /**
   * HTTPS-адрес для успешной оплаты.
   * @return successUrl
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SUCCESS_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public URI getSuccessUrl() {
    return successUrl;
  }


  @JsonProperty(value = JSON_PROPERTY_SUCCESS_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSuccessUrl(@javax.annotation.Nonnull URI successUrl) {
    this.successUrl = successUrl;
  }


  public CreateSbpPaymentRequest failedUrl(@javax.annotation.Nonnull URI failedUrl) {
    this.failedUrl = failedUrl;
    return this;
  }

  /**
   * HTTPS-адрес для отменённой оплаты.
   * @return failedUrl
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FAILED_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public URI getFailedUrl() {
    return failedUrl;
  }


  @JsonProperty(value = JSON_PROPERTY_FAILED_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFailedUrl(@javax.annotation.Nonnull URI failedUrl) {
    this.failedUrl = failedUrl;
  }


  public CreateSbpPaymentRequest deviceData(@javax.annotation.Nullable DeviceData deviceData) {
    this.deviceData = deviceData;
    return this;
  }

  /**
   * Get deviceData
   * @return deviceData
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DEVICE_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public DeviceData getDeviceData() {
    return deviceData;
  }


  @JsonProperty(value = JSON_PROPERTY_DEVICE_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeviceData(@javax.annotation.Nullable DeviceData deviceData) {
    this.deviceData = deviceData;
  }


  /**
   * Return true if this CreateSbpPaymentRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateSbpPaymentRequest createSbpPaymentRequest = (CreateSbpPaymentRequest) o;
    return Objects.equals(this.orderId, createSbpPaymentRequest.orderId) &&
        Objects.equals(this.amount, createSbpPaymentRequest.amount) &&
        Objects.equals(this.currency, createSbpPaymentRequest.currency) &&
        Objects.equals(this.description, createSbpPaymentRequest.description) &&
        Objects.equals(this.ip, createSbpPaymentRequest.ip) &&
        Objects.equals(this.callbackUrl, createSbpPaymentRequest.callbackUrl) &&
        Objects.equals(this.successUrl, createSbpPaymentRequest.successUrl) &&
        Objects.equals(this.failedUrl, createSbpPaymentRequest.failedUrl) &&
        Objects.equals(this.deviceData, createSbpPaymentRequest.deviceData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderId, amount, currency, description, ip, callbackUrl, successUrl, failedUrl, deviceData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateSbpPaymentRequest {\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    ip: ").append(toIndentedString(ip)).append("\n");
    sb.append("    callbackUrl: ").append(toIndentedString(callbackUrl)).append("\n");
    sb.append("    successUrl: ").append(toIndentedString(successUrl)).append("\n");
    sb.append("    failedUrl: ").append(toIndentedString(failedUrl)).append("\n");
    sb.append("    deviceData: ").append(toIndentedString(deviceData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `orderId` to the URL query string
    if (getOrderId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sorderId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOrderId()))));
    }

    // add `amount` to the URL query string
    if (getAmount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%samount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAmount()))));
    }

    // add `currency` to the URL query string
    if (getCurrency() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scurrency%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCurrency()))));
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdescription%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDescription()))));
    }

    // add `ip` to the URL query string
    if (getIp() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sip%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIp()))));
    }

    // add `callbackUrl` to the URL query string
    if (getCallbackUrl() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scallbackUrl%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCallbackUrl()))));
    }

    // add `successUrl` to the URL query string
    if (getSuccessUrl() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssuccessUrl%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSuccessUrl()))));
    }

    // add `failedUrl` to the URL query string
    if (getFailedUrl() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfailedUrl%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFailedUrl()))));
    }

    // add `deviceData` to the URL query string
    if (getDeviceData() != null) {
      joiner.add(getDeviceData().toUrlQueryString(prefix + "deviceData" + suffix));
    }

    return joiner.toString();
  }
}

