/*
 * OPayments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.opayments.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.opayments.sdk.ApiClient;
/**
 * DeviceData
 */
@JsonPropertyOrder({
  DeviceData.JSON_PROPERTY_PLATFORM_TYPE,
  DeviceData.JSON_PROPERTY_OS,
  DeviceData.JSON_PROPERTY_BROWSER,
  DeviceData.JSON_PROPERTY_LANGUAGE,
  DeviceData.JSON_PROPERTY_TIMEZONE_NAME,
  DeviceData.JSON_PROPERTY_USER_AGENT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-07T05:37:00.661163339Z[Etc/UTC]", comments = "Generator version: 7.26.0-SNAPSHOT")
public class DeviceData {
  /**
   * Gets or Sets platformType
   */
  public enum PlatformTypeEnum {
    MOBILE(String.valueOf("mobile")),
    
    DESKTOP(String.valueOf("desktop"));

    private String value;

    PlatformTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PlatformTypeEnum fromValue(String value) {
      for (PlatformTypeEnum b : PlatformTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PLATFORM_TYPE = "platformType";
  @javax.annotation.Nullable
  private PlatformTypeEnum platformType;

  public static final String JSON_PROPERTY_OS = "os";
  @javax.annotation.Nullable
  private String os;

  public static final String JSON_PROPERTY_BROWSER = "browser";
  @javax.annotation.Nullable
  private String browser;

  public static final String JSON_PROPERTY_LANGUAGE = "language";
  @javax.annotation.Nullable
  private String language;

  public static final String JSON_PROPERTY_TIMEZONE_NAME = "timezoneName";
  @javax.annotation.Nullable
  private String timezoneName;

  public static final String JSON_PROPERTY_USER_AGENT = "userAgent";
  @javax.annotation.Nullable
  private String userAgent;

  public DeviceData() { 
  }

  public DeviceData platformType(@javax.annotation.Nullable PlatformTypeEnum platformType) {
    this.platformType = platformType;
    return this;
  }

  /**
   * Get platformType
   * @return platformType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PLATFORM_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public PlatformTypeEnum getPlatformType() {
    return platformType;
  }


  @JsonProperty(value = JSON_PROPERTY_PLATFORM_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPlatformType(@javax.annotation.Nullable PlatformTypeEnum platformType) {
    this.platformType = platformType;
  }


  public DeviceData os(@javax.annotation.Nullable String os) {
    this.os = os;
    return this;
  }

  /**
   * Get os
   * @return os
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getOs() {
    return os;
  }


  @JsonProperty(value = JSON_PROPERTY_OS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOs(@javax.annotation.Nullable String os) {
    this.os = os;
  }


  public DeviceData browser(@javax.annotation.Nullable String browser) {
    this.browser = browser;
    return this;
  }

  /**
   * Get browser
   * @return browser
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BROWSER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getBrowser() {
    return browser;
  }


  @JsonProperty(value = JSON_PROPERTY_BROWSER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBrowser(@javax.annotation.Nullable String browser) {
    this.browser = browser;
  }


  public DeviceData language(@javax.annotation.Nullable String language) {
    this.language = language;
    return this;
  }

  /**
   * Get language
   * @return language
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LANGUAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getLanguage() {
    return language;
  }


  @JsonProperty(value = JSON_PROPERTY_LANGUAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLanguage(@javax.annotation.Nullable String language) {
    this.language = language;
  }


  public DeviceData timezoneName(@javax.annotation.Nullable String timezoneName) {
    this.timezoneName = timezoneName;
    return this;
  }

  /**
   * Get timezoneName
   * @return timezoneName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIMEZONE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTimezoneName() {
    return timezoneName;
  }


  @JsonProperty(value = JSON_PROPERTY_TIMEZONE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimezoneName(@javax.annotation.Nullable String timezoneName) {
    this.timezoneName = timezoneName;
  }


  public DeviceData userAgent(@javax.annotation.Nullable String userAgent) {
    this.userAgent = userAgent;
    return this;
  }

  /**
   * Get userAgent
   * @return userAgent
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_USER_AGENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getUserAgent() {
    return userAgent;
  }


  @JsonProperty(value = JSON_PROPERTY_USER_AGENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserAgent(@javax.annotation.Nullable String userAgent) {
    this.userAgent = userAgent;
  }


  /**
   * Return true if this DeviceData object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeviceData deviceData = (DeviceData) o;
    return Objects.equals(this.platformType, deviceData.platformType) &&
        Objects.equals(this.os, deviceData.os) &&
        Objects.equals(this.browser, deviceData.browser) &&
        Objects.equals(this.language, deviceData.language) &&
        Objects.equals(this.timezoneName, deviceData.timezoneName) &&
        Objects.equals(this.userAgent, deviceData.userAgent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(platformType, os, browser, language, timezoneName, userAgent);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceData {\n");
    sb.append("    platformType: ").append(toIndentedString(platformType)).append("\n");
    sb.append("    os: ").append(toIndentedString(os)).append("\n");
    sb.append("    browser: ").append(toIndentedString(browser)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    timezoneName: ").append(toIndentedString(timezoneName)).append("\n");
    sb.append("    userAgent: ").append(toIndentedString(userAgent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `platformType` to the URL query string
    if (getPlatformType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%splatformType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPlatformType()))));
    }

    // add `os` to the URL query string
    if (getOs() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sos%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOs()))));
    }

    // add `browser` to the URL query string
    if (getBrowser() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbrowser%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBrowser()))));
    }

    // add `language` to the URL query string
    if (getLanguage() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slanguage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLanguage()))));
    }

    // add `timezoneName` to the URL query string
    if (getTimezoneName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stimezoneName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTimezoneName()))));
    }

    // add `userAgent` to the URL query string
    if (getUserAgent() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%suserAgent%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUserAgent()))));
    }

    return joiner.toString();
  }
}

