/*
 * OPayments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.opayments.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.opayments.sdk.model.Payment;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.opayments.sdk.ApiClient;
/**
 * PaymentList
 */
@JsonPropertyOrder({
  PaymentList.JSON_PROPERTY_ITEMS,
  PaymentList.JSON_PROPERTY_NEXT_CURSOR,
  PaymentList.JSON_PROPERTY_HAS_MORE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-07T05:37:00.661163339Z[Etc/UTC]", comments = "Generator version: 7.26.0-SNAPSHOT")
public class PaymentList {
  public static final String JSON_PROPERTY_ITEMS = "items";
  @javax.annotation.Nonnull
  private List<Payment> items = new ArrayList<>();

  public static final String JSON_PROPERTY_NEXT_CURSOR = "nextCursor";
  @javax.annotation.Nonnull
  private String nextCursor;

  public static final String JSON_PROPERTY_HAS_MORE = "hasMore";
  @javax.annotation.Nonnull
  private Boolean hasMore;

  public PaymentList() { 
  }

  public PaymentList items(@javax.annotation.Nonnull List<Payment> items) {
    this.items = items;
    return this;
  }

  public PaymentList addItemsItem(Payment itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<>();
    }
    this.items.add(itemsItem);
    return this;
  }

  /**
   * Get items
   * @return items
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ITEMS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<Payment> getItems() {
    return items;
  }


  @JsonProperty(value = JSON_PROPERTY_ITEMS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setItems(@javax.annotation.Nonnull List<Payment> items) {
    this.items = items;
  }


  public PaymentList nextCursor(@javax.annotation.Nonnull String nextCursor) {
    this.nextCursor = nextCursor;
    return this;
  }

  /**
   * Get nextCursor
   * @return nextCursor
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NEXT_CURSOR, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getNextCursor() {
    return nextCursor;
  }


  @JsonProperty(value = JSON_PROPERTY_NEXT_CURSOR, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNextCursor(@javax.annotation.Nonnull String nextCursor) {
    this.nextCursor = nextCursor;
  }


  public PaymentList hasMore(@javax.annotation.Nonnull Boolean hasMore) {
    this.hasMore = hasMore;
    return this;
  }

  /**
   * Get hasMore
   * @return hasMore
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_HAS_MORE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getHasMore() {
    return hasMore;
  }


  @JsonProperty(value = JSON_PROPERTY_HAS_MORE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHasMore(@javax.annotation.Nonnull Boolean hasMore) {
    this.hasMore = hasMore;
  }


  /**
   * Return true if this PaymentList object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentList paymentList = (PaymentList) o;
    return Objects.equals(this.items, paymentList.items) &&
        Objects.equals(this.nextCursor, paymentList.nextCursor) &&
        Objects.equals(this.hasMore, paymentList.hasMore);
  }

  @Override
  public int hashCode() {
    return Objects.hash(items, nextCursor, hasMore);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentList {\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    nextCursor: ").append(toIndentedString(nextCursor)).append("\n");
    sb.append("    hasMore: ").append(toIndentedString(hasMore)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `items` to the URL query string
    if (getItems() != null) {
      for (int i = 0; i < getItems().size(); i++) {
        if (getItems().get(i) != null) {
          joiner.add(getItems().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sitems%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `nextCursor` to the URL query string
    if (getNextCursor() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%snextCursor%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getNextCursor()))));
    }

    // add `hasMore` to the URL query string
    if (getHasMore() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%shasMore%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHasMore()))));
    }

    return joiner.toString();
  }
}

