/*
 * OPayments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.opayments.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.opayments.sdk.ApiClient;
/**
 * PendingRefund
 */
@JsonPropertyOrder({
  PendingRefund.JSON_PROPERTY_PAYMENT_ID,
  PendingRefund.JSON_PROPERTY_AMOUNT,
  PendingRefund.JSON_PROPERTY_CURRENCY,
  PendingRefund.JSON_PROPERTY_STATUS,
  PendingRefund.JSON_PROPERTY_REASON,
  PendingRefund.JSON_PROPERTY_FAILURE_CODE,
  PendingRefund.JSON_PROPERTY_FAILURE_MESSAGE,
  PendingRefund.JSON_PROPERTY_ACCEPTED_AT,
  PendingRefund.JSON_PROPERTY_DECLINED_AT,
  PendingRefund.JSON_PROPERTY_CREATED_AT,
  PendingRefund.JSON_PROPERTY_UPDATED_AT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-07T05:37:00.661163339Z[Etc/UTC]", comments = "Generator version: 7.26.0-SNAPSHOT")
public class PendingRefund {
  public static final String JSON_PROPERTY_PAYMENT_ID = "paymentId";
  @javax.annotation.Nonnull
  private UUID paymentId;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  @javax.annotation.Nonnull
  private Integer amount;

  /**
   * Gets or Sets currency
   */
  public enum CurrencyEnum {
    RUB(String.valueOf("RUB"));

    private String value;

    CurrencyEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static CurrencyEnum fromValue(String value) {
      for (CurrencyEnum b : CurrencyEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @javax.annotation.Nonnull
  private CurrencyEnum currency;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    PENDING(String.valueOf("pending"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nonnull
  private StatusEnum status;

  public static final String JSON_PROPERTY_REASON = "reason";
  @javax.annotation.Nullable
  private String reason;

  public static final String JSON_PROPERTY_FAILURE_CODE = "failureCode";
  @javax.annotation.Nullable
  private String failureCode;

  public static final String JSON_PROPERTY_FAILURE_MESSAGE = "failureMessage";
  @javax.annotation.Nullable
  private String failureMessage;

  public static final String JSON_PROPERTY_ACCEPTED_AT = "acceptedAt";
  @javax.annotation.Nullable
  private OffsetDateTime acceptedAt;

  public static final String JSON_PROPERTY_DECLINED_AT = "declinedAt";
  @javax.annotation.Nullable
  private OffsetDateTime declinedAt;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @javax.annotation.Nonnull
  private OffsetDateTime updatedAt;

  public PendingRefund() { 
  }

  public PendingRefund paymentId(@javax.annotation.Nonnull UUID paymentId) {
    this.paymentId = paymentId;
    return this;
  }

  /**
   * Get paymentId
   * @return paymentId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PAYMENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getPaymentId() {
    return paymentId;
  }


  @JsonProperty(value = JSON_PROPERTY_PAYMENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPaymentId(@javax.annotation.Nonnull UUID paymentId) {
    this.paymentId = paymentId;
  }


  public PendingRefund amount(@javax.annotation.Nonnull Integer amount) {
    this.amount = amount;
    return this;
  }

  /**
   * Сумма в копейках.
   * minimum: 1
   * @return amount
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AMOUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getAmount() {
    return amount;
  }


  @JsonProperty(value = JSON_PROPERTY_AMOUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmount(@javax.annotation.Nonnull Integer amount) {
    this.amount = amount;
  }


  public PendingRefund currency(@javax.annotation.Nonnull CurrencyEnum currency) {
    this.currency = currency;
    return this;
  }

  /**
   * Get currency
   * @return currency
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public CurrencyEnum getCurrency() {
    return currency;
  }


  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCurrency(@javax.annotation.Nonnull CurrencyEnum currency) {
    this.currency = currency;
  }


  public PendingRefund status(@javax.annotation.Nonnull StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@javax.annotation.Nonnull StatusEnum status) {
    this.status = status;
  }


  public PendingRefund reason(@javax.annotation.Nullable String reason) {
    this.reason = reason;
    return this;
  }

  /**
   * Get reason
   * @return reason
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REASON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getReason() {
    return reason;
  }


  @JsonProperty(value = JSON_PROPERTY_REASON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReason(@javax.annotation.Nullable String reason) {
    this.reason = reason;
  }


  public PendingRefund failureCode(@javax.annotation.Nullable String failureCode) {
    this.failureCode = failureCode;
    return this;
  }

  /**
   * Get failureCode
   * @return failureCode
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FAILURE_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFailureCode() {
    return failureCode;
  }


  @JsonProperty(value = JSON_PROPERTY_FAILURE_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFailureCode(@javax.annotation.Nullable String failureCode) {
    this.failureCode = failureCode;
  }


  public PendingRefund failureMessage(@javax.annotation.Nullable String failureMessage) {
    this.failureMessage = failureMessage;
    return this;
  }

  /**
   * Get failureMessage
   * @return failureMessage
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FAILURE_MESSAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFailureMessage() {
    return failureMessage;
  }


  @JsonProperty(value = JSON_PROPERTY_FAILURE_MESSAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFailureMessage(@javax.annotation.Nullable String failureMessage) {
    this.failureMessage = failureMessage;
  }


  public PendingRefund acceptedAt(@javax.annotation.Nullable OffsetDateTime acceptedAt) {
    this.acceptedAt = acceptedAt;
    return this;
  }

  /**
   * Get acceptedAt
   * @return acceptedAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACCEPTED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getAcceptedAt() {
    return acceptedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_ACCEPTED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAcceptedAt(@javax.annotation.Nullable OffsetDateTime acceptedAt) {
    this.acceptedAt = acceptedAt;
  }


  public PendingRefund declinedAt(@javax.annotation.Nullable OffsetDateTime declinedAt) {
    this.declinedAt = declinedAt;
    return this;
  }

  /**
   * Get declinedAt
   * @return declinedAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DECLINED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getDeclinedAt() {
    return declinedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_DECLINED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeclinedAt(@javax.annotation.Nullable OffsetDateTime declinedAt) {
    this.declinedAt = declinedAt;
  }


  public PendingRefund createdAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public PendingRefund updatedAt(@javax.annotation.Nonnull OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUpdatedAt(@javax.annotation.Nonnull OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  /**
   * Return true if this PendingRefund object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PendingRefund pendingRefund = (PendingRefund) o;
    return Objects.equals(this.paymentId, pendingRefund.paymentId) &&
        Objects.equals(this.amount, pendingRefund.amount) &&
        Objects.equals(this.currency, pendingRefund.currency) &&
        Objects.equals(this.status, pendingRefund.status) &&
        Objects.equals(this.reason, pendingRefund.reason) &&
        Objects.equals(this.failureCode, pendingRefund.failureCode) &&
        Objects.equals(this.failureMessage, pendingRefund.failureMessage) &&
        Objects.equals(this.acceptedAt, pendingRefund.acceptedAt) &&
        Objects.equals(this.declinedAt, pendingRefund.declinedAt) &&
        Objects.equals(this.createdAt, pendingRefund.createdAt) &&
        Objects.equals(this.updatedAt, pendingRefund.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paymentId, amount, currency, status, reason, failureCode, failureMessage, acceptedAt, declinedAt, createdAt, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PendingRefund {\n");
    sb.append("    paymentId: ").append(toIndentedString(paymentId)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    failureCode: ").append(toIndentedString(failureCode)).append("\n");
    sb.append("    failureMessage: ").append(toIndentedString(failureMessage)).append("\n");
    sb.append("    acceptedAt: ").append(toIndentedString(acceptedAt)).append("\n");
    sb.append("    declinedAt: ").append(toIndentedString(declinedAt)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `paymentId` to the URL query string
    if (getPaymentId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spaymentId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPaymentId()))));
    }

    // add `amount` to the URL query string
    if (getAmount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%samount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAmount()))));
    }

    // add `currency` to the URL query string
    if (getCurrency() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scurrency%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCurrency()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `reason` to the URL query string
    if (getReason() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sreason%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getReason()))));
    }

    // add `failureCode` to the URL query string
    if (getFailureCode() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfailureCode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFailureCode()))));
    }

    // add `failureMessage` to the URL query string
    if (getFailureMessage() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfailureMessage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFailureMessage()))));
    }

    // add `acceptedAt` to the URL query string
    if (getAcceptedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sacceptedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAcceptedAt()))));
    }

    // add `declinedAt` to the URL query string
    if (getDeclinedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdeclinedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDeclinedAt()))));
    }

    // add `createdAt` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screatedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedAt()))));
    }

    // add `updatedAt` to the URL query string
    if (getUpdatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%supdatedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUpdatedAt()))));
    }

    return joiner.toString();
  }
}

