/*
 * OPayments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.opayments.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.opayments.sdk.model.FinalPayment;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.opayments.sdk.ApiClient;
/**
 * PostpaymentWebhookNotification
 */
@JsonPropertyOrder({
  PostpaymentWebhookNotification.JSON_PROPERTY_NOTIFICATION_ID,
  PostpaymentWebhookNotification.JSON_PROPERTY_NOTIFICATION_TYPE,
  PostpaymentWebhookNotification.JSON_PROPERTY_NOTIFICATION_DATE,
  PostpaymentWebhookNotification.JSON_PROPERTY_PAYMENT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-07T05:37:00.661163339Z[Etc/UTC]", comments = "Generator version: 7.26.0-SNAPSHOT")
public class PostpaymentWebhookNotification {
  public static final String JSON_PROPERTY_NOTIFICATION_ID = "notificationId";
  @javax.annotation.Nonnull
  private UUID notificationId;

  /**
   * Gets or Sets notificationType
   */
  public enum NotificationTypeEnum {
    POSTPAYMENT(String.valueOf("postpayment"));

    private String value;

    NotificationTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static NotificationTypeEnum fromValue(String value) {
      for (NotificationTypeEnum b : NotificationTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_NOTIFICATION_TYPE = "notificationType";
  @javax.annotation.Nonnull
  private NotificationTypeEnum notificationType;

  public static final String JSON_PROPERTY_NOTIFICATION_DATE = "notificationDate";
  @javax.annotation.Nonnull
  private OffsetDateTime notificationDate;

  public static final String JSON_PROPERTY_PAYMENT = "payment";
  @javax.annotation.Nonnull
  private FinalPayment payment;

  public PostpaymentWebhookNotification() { 
  }

  public PostpaymentWebhookNotification notificationId(@javax.annotation.Nonnull UUID notificationId) {
    this.notificationId = notificationId;
    return this;
  }

  /**
   * Get notificationId
   * @return notificationId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NOTIFICATION_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getNotificationId() {
    return notificationId;
  }


  @JsonProperty(value = JSON_PROPERTY_NOTIFICATION_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNotificationId(@javax.annotation.Nonnull UUID notificationId) {
    this.notificationId = notificationId;
  }


  public PostpaymentWebhookNotification notificationType(@javax.annotation.Nonnull NotificationTypeEnum notificationType) {
    this.notificationType = notificationType;
    return this;
  }

  /**
   * Get notificationType
   * @return notificationType
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NOTIFICATION_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public NotificationTypeEnum getNotificationType() {
    return notificationType;
  }


  @JsonProperty(value = JSON_PROPERTY_NOTIFICATION_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNotificationType(@javax.annotation.Nonnull NotificationTypeEnum notificationType) {
    this.notificationType = notificationType;
  }


  public PostpaymentWebhookNotification notificationDate(@javax.annotation.Nonnull OffsetDateTime notificationDate) {
    this.notificationDate = notificationDate;
    return this;
  }

  /**
   * Get notificationDate
   * @return notificationDate
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NOTIFICATION_DATE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getNotificationDate() {
    return notificationDate;
  }


  @JsonProperty(value = JSON_PROPERTY_NOTIFICATION_DATE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNotificationDate(@javax.annotation.Nonnull OffsetDateTime notificationDate) {
    this.notificationDate = notificationDate;
  }


  public PostpaymentWebhookNotification payment(@javax.annotation.Nonnull FinalPayment payment) {
    this.payment = payment;
    return this;
  }

  /**
   * Get payment
   * @return payment
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PAYMENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public FinalPayment getPayment() {
    return payment;
  }


  @JsonProperty(value = JSON_PROPERTY_PAYMENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPayment(@javax.annotation.Nonnull FinalPayment payment) {
    this.payment = payment;
  }


  /**
   * Return true if this PostpaymentWebhookNotification object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostpaymentWebhookNotification postpaymentWebhookNotification = (PostpaymentWebhookNotification) o;
    return Objects.equals(this.notificationId, postpaymentWebhookNotification.notificationId) &&
        Objects.equals(this.notificationType, postpaymentWebhookNotification.notificationType) &&
        Objects.equals(this.notificationDate, postpaymentWebhookNotification.notificationDate) &&
        Objects.equals(this.payment, postpaymentWebhookNotification.payment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(notificationId, notificationType, notificationDate, payment);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostpaymentWebhookNotification {\n");
    sb.append("    notificationId: ").append(toIndentedString(notificationId)).append("\n");
    sb.append("    notificationType: ").append(toIndentedString(notificationType)).append("\n");
    sb.append("    notificationDate: ").append(toIndentedString(notificationDate)).append("\n");
    sb.append("    payment: ").append(toIndentedString(payment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `notificationId` to the URL query string
    if (getNotificationId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%snotificationId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getNotificationId()))));
    }

    // add `notificationType` to the URL query string
    if (getNotificationType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%snotificationType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getNotificationType()))));
    }

    // add `notificationDate` to the URL query string
    if (getNotificationDate() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%snotificationDate%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getNotificationDate()))));
    }

    // add `payment` to the URL query string
    if (getPayment() != null) {
      joiner.add(getPayment().toUrlQueryString(prefix + "payment" + suffix));
    }

    return joiner.toString();
  }
}

