/*
 * OPayments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.opayments.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.opayments.sdk.ApiClient;
/**
 * PrepaymentPayment
 */
@JsonPropertyOrder({
  PrepaymentPayment.JSON_PROPERTY_PAYMENT_ID,
  PrepaymentPayment.JSON_PROPERTY_ORDER_ID,
  PrepaymentPayment.JSON_PROPERTY_AMOUNT,
  PrepaymentPayment.JSON_PROPERTY_CURRENCY,
  PrepaymentPayment.JSON_PROPERTY_DESCRIPTION,
  PrepaymentPayment.JSON_PROPERTY_PAYMENT_METHOD,
  PrepaymentPayment.JSON_PROPERTY_STATUS,
  PrepaymentPayment.JSON_PROPERTY_PAYMENT_URL,
  PrepaymentPayment.JSON_PROPERTY_EXPIRES_AT,
  PrepaymentPayment.JSON_PROPERTY_FAILURE_CODE,
  PrepaymentPayment.JSON_PROPERTY_FAILURE_MESSAGE,
  PrepaymentPayment.JSON_PROPERTY_COMPLETED_AT,
  PrepaymentPayment.JSON_PROPERTY_CREATED_AT,
  PrepaymentPayment.JSON_PROPERTY_UPDATED_AT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-07T05:37:00.661163339Z[Etc/UTC]", comments = "Generator version: 7.26.0-SNAPSHOT")
public class PrepaymentPayment {
  public static final String JSON_PROPERTY_PAYMENT_ID = "paymentId";
  @javax.annotation.Nonnull
  private UUID paymentId;

  public static final String JSON_PROPERTY_ORDER_ID = "orderId";
  @javax.annotation.Nonnull
  private String orderId;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  @javax.annotation.Nonnull
  private Integer amount;

  /**
   * Gets or Sets currency
   */
  public enum CurrencyEnum {
    RUB(String.valueOf("RUB"));

    private String value;

    CurrencyEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static CurrencyEnum fromValue(String value) {
      for (CurrencyEnum b : CurrencyEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @javax.annotation.Nonnull
  private CurrencyEnum currency;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  /**
   * Gets or Sets paymentMethod
   */
  public enum PaymentMethodEnum {
    SBP(String.valueOf("sbp")),
    
    TPAY(String.valueOf("tpay"));

    private String value;

    PaymentMethodEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PaymentMethodEnum fromValue(String value) {
      for (PaymentMethodEnum b : PaymentMethodEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PAYMENT_METHOD = "paymentMethod";
  @javax.annotation.Nonnull
  private PaymentMethodEnum paymentMethod;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    PENDING(String.valueOf("pending"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nonnull
  private StatusEnum status;

  public static final String JSON_PROPERTY_PAYMENT_URL = "paymentUrl";
  @javax.annotation.Nullable
  private URI paymentUrl;

  public static final String JSON_PROPERTY_EXPIRES_AT = "expiresAt";
  @javax.annotation.Nullable
  private OffsetDateTime expiresAt;

  public static final String JSON_PROPERTY_FAILURE_CODE = "failureCode";
  @javax.annotation.Nullable
  private String failureCode;

  public static final String JSON_PROPERTY_FAILURE_MESSAGE = "failureMessage";
  @javax.annotation.Nullable
  private String failureMessage;

  public static final String JSON_PROPERTY_COMPLETED_AT = "completedAt";
  @javax.annotation.Nullable
  private OffsetDateTime completedAt;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @javax.annotation.Nonnull
  private OffsetDateTime updatedAt;

  public PrepaymentPayment() { 
  }

  public PrepaymentPayment paymentId(@javax.annotation.Nonnull UUID paymentId) {
    this.paymentId = paymentId;
    return this;
  }

  /**
   * Get paymentId
   * @return paymentId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PAYMENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getPaymentId() {
    return paymentId;
  }


  @JsonProperty(value = JSON_PROPERTY_PAYMENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPaymentId(@javax.annotation.Nonnull UUID paymentId) {
    this.paymentId = paymentId;
  }


  public PrepaymentPayment orderId(@javax.annotation.Nonnull String orderId) {
    this.orderId = orderId;
    return this;
  }

  /**
   * Get orderId
   * @return orderId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ORDER_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getOrderId() {
    return orderId;
  }


  @JsonProperty(value = JSON_PROPERTY_ORDER_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOrderId(@javax.annotation.Nonnull String orderId) {
    this.orderId = orderId;
  }


  public PrepaymentPayment amount(@javax.annotation.Nonnull Integer amount) {
    this.amount = amount;
    return this;
  }

  /**
   * Сумма в копейках.
   * minimum: 1
   * @return amount
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AMOUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getAmount() {
    return amount;
  }


  @JsonProperty(value = JSON_PROPERTY_AMOUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmount(@javax.annotation.Nonnull Integer amount) {
    this.amount = amount;
  }


  public PrepaymentPayment currency(@javax.annotation.Nonnull CurrencyEnum currency) {
    this.currency = currency;
    return this;
  }

  /**
   * Get currency
   * @return currency
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public CurrencyEnum getCurrency() {
    return currency;
  }


  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCurrency(@javax.annotation.Nonnull CurrencyEnum currency) {
    this.currency = currency;
  }


  public PrepaymentPayment description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public PrepaymentPayment paymentMethod(@javax.annotation.Nonnull PaymentMethodEnum paymentMethod) {
    this.paymentMethod = paymentMethod;
    return this;
  }

  /**
   * Get paymentMethod
   * @return paymentMethod
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PAYMENT_METHOD, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public PaymentMethodEnum getPaymentMethod() {
    return paymentMethod;
  }


  @JsonProperty(value = JSON_PROPERTY_PAYMENT_METHOD, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPaymentMethod(@javax.annotation.Nonnull PaymentMethodEnum paymentMethod) {
    this.paymentMethod = paymentMethod;
  }


  public PrepaymentPayment status(@javax.annotation.Nonnull StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@javax.annotation.Nonnull StatusEnum status) {
    this.status = status;
  }


  public PrepaymentPayment paymentUrl(@javax.annotation.Nullable URI paymentUrl) {
    this.paymentUrl = paymentUrl;
    return this;
  }

  /**
   * Адрес оплаты для платежа в статусе pending.
   * @return paymentUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PAYMENT_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public URI getPaymentUrl() {
    return paymentUrl;
  }


  @JsonProperty(value = JSON_PROPERTY_PAYMENT_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaymentUrl(@javax.annotation.Nullable URI paymentUrl) {
    this.paymentUrl = paymentUrl;
  }


  public PrepaymentPayment expiresAt(@javax.annotation.Nullable OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
    return this;
  }

  /**
   * Get expiresAt
   * @return expiresAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXPIRES_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getExpiresAt() {
    return expiresAt;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPIRES_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpiresAt(@javax.annotation.Nullable OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
  }


  public PrepaymentPayment failureCode(@javax.annotation.Nullable String failureCode) {
    this.failureCode = failureCode;
    return this;
  }

  /**
   * Get failureCode
   * @return failureCode
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FAILURE_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFailureCode() {
    return failureCode;
  }


  @JsonProperty(value = JSON_PROPERTY_FAILURE_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFailureCode(@javax.annotation.Nullable String failureCode) {
    this.failureCode = failureCode;
  }


  public PrepaymentPayment failureMessage(@javax.annotation.Nullable String failureMessage) {
    this.failureMessage = failureMessage;
    return this;
  }

  /**
   * Get failureMessage
   * @return failureMessage
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FAILURE_MESSAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFailureMessage() {
    return failureMessage;
  }


  @JsonProperty(value = JSON_PROPERTY_FAILURE_MESSAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFailureMessage(@javax.annotation.Nullable String failureMessage) {
    this.failureMessage = failureMessage;
  }


  public PrepaymentPayment completedAt(@javax.annotation.Nullable OffsetDateTime completedAt) {
    this.completedAt = completedAt;
    return this;
  }

  /**
   * Get completedAt
   * @return completedAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMPLETED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getCompletedAt() {
    return completedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_COMPLETED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCompletedAt(@javax.annotation.Nullable OffsetDateTime completedAt) {
    this.completedAt = completedAt;
  }


  public PrepaymentPayment createdAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public PrepaymentPayment updatedAt(@javax.annotation.Nonnull OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUpdatedAt(@javax.annotation.Nonnull OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  /**
   * Return true if this PrepaymentPayment object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PrepaymentPayment prepaymentPayment = (PrepaymentPayment) o;
    return Objects.equals(this.paymentId, prepaymentPayment.paymentId) &&
        Objects.equals(this.orderId, prepaymentPayment.orderId) &&
        Objects.equals(this.amount, prepaymentPayment.amount) &&
        Objects.equals(this.currency, prepaymentPayment.currency) &&
        Objects.equals(this.description, prepaymentPayment.description) &&
        Objects.equals(this.paymentMethod, prepaymentPayment.paymentMethod) &&
        Objects.equals(this.status, prepaymentPayment.status) &&
        Objects.equals(this.paymentUrl, prepaymentPayment.paymentUrl) &&
        Objects.equals(this.expiresAt, prepaymentPayment.expiresAt) &&
        Objects.equals(this.failureCode, prepaymentPayment.failureCode) &&
        Objects.equals(this.failureMessage, prepaymentPayment.failureMessage) &&
        Objects.equals(this.completedAt, prepaymentPayment.completedAt) &&
        Objects.equals(this.createdAt, prepaymentPayment.createdAt) &&
        Objects.equals(this.updatedAt, prepaymentPayment.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paymentId, orderId, amount, currency, description, paymentMethod, status, paymentUrl, expiresAt, failureCode, failureMessage, completedAt, createdAt, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PrepaymentPayment {\n");
    sb.append("    paymentId: ").append(toIndentedString(paymentId)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    paymentMethod: ").append(toIndentedString(paymentMethod)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    paymentUrl: ").append(toIndentedString(paymentUrl)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("    failureCode: ").append(toIndentedString(failureCode)).append("\n");
    sb.append("    failureMessage: ").append(toIndentedString(failureMessage)).append("\n");
    sb.append("    completedAt: ").append(toIndentedString(completedAt)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `paymentId` to the URL query string
    if (getPaymentId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spaymentId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPaymentId()))));
    }

    // add `orderId` to the URL query string
    if (getOrderId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sorderId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOrderId()))));
    }

    // add `amount` to the URL query string
    if (getAmount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%samount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAmount()))));
    }

    // add `currency` to the URL query string
    if (getCurrency() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scurrency%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCurrency()))));
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdescription%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDescription()))));
    }

    // add `paymentMethod` to the URL query string
    if (getPaymentMethod() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spaymentMethod%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPaymentMethod()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `paymentUrl` to the URL query string
    if (getPaymentUrl() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spaymentUrl%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPaymentUrl()))));
    }

    // add `expiresAt` to the URL query string
    if (getExpiresAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sexpiresAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExpiresAt()))));
    }

    // add `failureCode` to the URL query string
    if (getFailureCode() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfailureCode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFailureCode()))));
    }

    // add `failureMessage` to the URL query string
    if (getFailureMessage() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfailureMessage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFailureMessage()))));
    }

    // add `completedAt` to the URL query string
    if (getCompletedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scompletedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCompletedAt()))));
    }

    // add `createdAt` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screatedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedAt()))));
    }

    // add `updatedAt` to the URL query string
    if (getUpdatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%supdatedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUpdatedAt()))));
    }

    return joiner.toString();
  }
}

